services:
  studentusauth:
    container_name: studentusauth.app
    build:
      context: .
      dockerfile: StudentusAuth/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: postgres:17.5-alpine
    container_name: studentusauth.database
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: